"""create inventory_items

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 16:41:01.731436
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('vial_size_mg', sa.Float(), nullable=True),
    sa.Column('medium', sa.Enum('Lyophilized', 'Liquid', 'Autoinjector', 'Inhaler', 'Pill', 'Drops', 'Salve', name='medium', native_enum=False, length=20), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('coa_filename', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_cents IS NULL OR cost_cents >= 0', name='ck_inventory_cost_nonneg'),
    sa.CheckConstraint('count >= 0', name='ck_inventory_count_nonneg'),
    sa.CheckConstraint('vial_size_mg IS NULL OR vial_size_mg > 0', name='ck_inventory_vial_size_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
