"""inventory order and coa details

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 16:53:35.250006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('shipped_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('arrival_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('coa_vial_size_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coa_purity_pct', sa.Float(), nullable=True))
        batch_op.create_check_constraint(
            'ck_inventory_coa_vial_size_pos', 'coa_vial_size_mg IS NULL OR coa_vial_size_mg > 0')
        batch_op.create_check_constraint(
            'ck_inventory_coa_purity_range',
            'coa_purity_pct IS NULL OR (coa_purity_pct >= 0 AND coa_purity_pct <= 100)')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('ck_inventory_coa_purity_range', type_='check')
        batch_op.drop_constraint('ck_inventory_coa_vial_size_pos', type_='check')
        batch_op.drop_column('coa_purity_pct')
        batch_op.drop_column('coa_vial_size_mg')
        batch_op.drop_column('arrival_date')
        batch_op.drop_column('shipped_date')
        batch_op.drop_column('order_date')
        batch_op.drop_column('lot_number')

    # ### end Alembic commands ###
