"""protocols

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 18:50:38.904654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peptides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120, collation='NOCASE'), nullable=False),
    sa.Column('aliases', sa.String(length=300), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('dose_low', sa.Float(), nullable=True),
    sa.Column('dose_mid', sa.Float(), nullable=True),
    sa.Column('dose_high', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.Enum('mg', 'mcg', 'IU', name='doseunit', native_enum=False, length=20), nullable=True),
    sa.Column('typical_frequency', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('card', 'starter', 'custom', name='peptidesource', native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('titration_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_peptides',
    sa.Column('goal', sa.String(length=40), nullable=False),
    sa.Column('peptide_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peptide_id'], ['peptides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal', 'peptide_id')
    )
    op.create_table('protocol_goals',
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('protocol_id', 'goal')
    )
    op.create_table('protocol_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('peptide_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.Enum('mg', 'mcg', 'IU', name='doseunit', native_enum=False, length=20), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'eod', 'every_n_days', 'weekdays', 'weekly', 'as_needed', name='frequency', native_enum=False, length=20), nullable=False),
    sa.Column('every_n_days', sa.Integer(), nullable=True),
    sa.Column('weekdays', sa.String(length=7), nullable=True),
    sa.Column('time_of_day', sa.Enum('am', 'pm', 'bedtime', 'any', name='timeofday', native_enum=False, length=20), nullable=False),
    sa.Column('route', sa.Enum('subq', 'im', 'oral', 'nasal', 'topical', 'other', name='route', native_enum=False, length=20), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.CheckConstraint('dose IS NULL OR dose > 0', name='ck_protocol_item_dose_pos'),
    sa.CheckConstraint('every_n_days IS NULL OR every_n_days >= 2', name='ck_protocol_item_every_n_days'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['peptide_id'], ['peptides.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titration_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_item_id', sa.Integer(), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('end_week', sa.Integer(), nullable=True),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.CheckConstraint('dose > 0', name='ck_titration_dose_pos'),
    sa.CheckConstraint('end_week IS NULL OR end_week >= start_week', name='ck_titration_end_week'),
    sa.CheckConstraint('start_week >= 1', name='ck_titration_start_week'),
    sa.ForeignKeyConstraint(['protocol_item_id'], ['protocol_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    seed()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titration_steps')
    op.drop_table('protocol_items')
    op.drop_table('protocol_goals')
    op.drop_table('goal_peptides')
    op.drop_table('protocols')
    op.drop_table('peptides')
    # ### end Alembic commands ###


# ---------------------------------------------------------------- seed data
# Names only, in the order of the owner's 100 peptide cards (card_number = position + 1).
CARD_PEPTIDES = [
    "AOD-9604", "BPC-157", "CJC-1295", "CJC-1295 + Ipamorelin", "CJC-1295 DAC", "DSIP", "Epitalon",
    "FOXO4-DRI", "GHK-Cu", "GHRP-2", "GHRP-6", "Gonadorelin (GnRH)", "Hexarelin", "Humanin", "IGF-1",
    "IGF-1 DES (1-3)", "IGF-1 LR3", "Ipamorelin", "Kisspeptin-10", "Kisspeptin-54", "Larazotide acetate",
    "MOTS-c", "Melanotan I (Afamelanotide)", "Melanotan II", "Nesfatin-1", "PACAP", "PEG-MGF",
    "PT-141 (Bremelanotide)", "Selank", "Semax", "Sermorelin", "Tesamorelin", "Tesofensine", "TB-500",
    "Thymosin alpha-1", "Tirzepatide", "Semaglutide", "Liraglutide", "Dulaglutide", "Exenatide",
    "Lixisenatide", "Efpeglenatide", "Retatrutide", "Survodutide", "Cagrilintide", "Amylin", "Pramlintide",
    "Oxyntomodulin", "Mazdutide", "AMG-133 (MariTide)", "GLP-1", "GIP", "Glucagon", "PYY (Peptide YY)",
    "OXM + GLP-1 (co-agonists)", "Secretin", "Cholecystokinin (CCK)", "VIP", "Somatostatin", "Octreotide",
    "Lanreotide", "Pasireotide", "Calcitonin", "Teriparatide (PTH 1-34)", "Abaloparatide", "PTH (1-84)",
    "Elcatonin", "Leuprorelin", "Goserelin", "Triptorelin", "Degarelix", "Buserelin", "Nafarelin",
    "Histrelin", "Desmopressin", "Vasopressin", "Oxytocin", "Angiotensin II", "Ecallantide", "Icatibant",
    "Ziconotide", "Linaclotide", "Plecanatide", "Teduglutide", "GLP-2 analogues", "Relamorelin",
    "Elamipretide (SS-31)", "PNC-27", "Cibinetide", "Avexitide", "Luspatercept", "Sotatercept",
    "Anamorelin", "Pegvisomant", "Mecasermin", "Mecasermin rinfabate", "Carbetocin", "Atosiban",
    "Setmelanotide", "Bepirovirsen",
]

# Common in stacks but not among the cards.
STARTER_PEPTIDES = ["KPV", "NAD+", "Glutathione", "LL-37", "Pinealon"]

# Suggested stack per goal, in order. Authored for Amide; editable later in the Library.
GOAL_STACKS = {
    "fat-loss": ["Retatrutide", "Tirzepatide", "Tesamorelin", "AOD-9604", "MOTS-c"],
    "muscle-recovery": ["BPC-157", "TB-500", "CJC-1295 + Ipamorelin", "IGF-1 LR3", "PEG-MGF"],
    "gh-performance": ["CJC-1295 + Ipamorelin", "Tesamorelin", "Sermorelin", "Ipamorelin", "GHRP-2"],
    "longevity": ["Epitalon", "MOTS-c", "Elamipretide (SS-31)", "Humanin", "NAD+"],
    "skin-beauty": ["GHK-Cu", "BPC-157", "KPV", "Melanotan I (Afamelanotide)"],
    "wellness": ["Thymosin alpha-1", "BPC-157", "Selank", "Semax", "Glutathione"],
    "glp1-weight": ["Semaglutide", "Tirzepatide", "Retatrutide", "Cagrilintide", "Liraglutide"],
    "sleep-recovery": ["DSIP", "CJC-1295 + Ipamorelin", "Epitalon", "Pinealon"],
}


def seed() -> None:
    conn = op.get_bind()
    if conn.execute(sa.text("SELECT COUNT(*) FROM peptides")).scalar():
        return  # never overwrite the owner's library

    peptides = sa.table("peptides", sa.column("name"), sa.column("card_number"), sa.column("source"))
    op.bulk_insert(peptides,
                   [{"name": n, "card_number": i + 1, "source": "card"} for i, n in enumerate(CARD_PEPTIDES)]
                   + [{"name": n, "card_number": None, "source": "starter"} for n in STARTER_PEPTIDES])

    ids = dict(conn.execute(sa.text("SELECT name, id FROM peptides")).all())
    goal_peptides = sa.table("goal_peptides", sa.column("goal"), sa.column("peptide_id"), sa.column("position"))
    op.bulk_insert(goal_peptides, [
        {"goal": goal, "peptide_id": ids[name], "position": pos}
        for goal, names in GOAL_STACKS.items() for pos, name in enumerate(names)
    ])
