"""inventory foundations

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-23 19:13:10.664746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200, collation='NOCASE'), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('contact_info', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_vendor_owner_name')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vial_size_unit', sa.Enum('mg', 'mcg', 'IU', name='doseunit', native_enum=False, length=20), nullable=False, server_default='mg'))
        batch_op.add_column(sa.Column('volume_ml', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('units_per_package', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.Enum('fridge', 'freezer', 'room_temp', name='storagelocation', native_enum=False, length=20), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_items_vendor_id_vendors', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_check_constraint('ck_inventory_volume_pos', 'volume_ml IS NULL OR volume_ml > 0')
        batch_op.create_check_constraint('ck_inventory_units_pkg_pos', 'units_per_package IS NULL OR units_per_package > 0')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('ck_inventory_units_pkg_pos', type_='check')
        batch_op.drop_constraint('ck_inventory_volume_pos', type_='check')
        batch_op.drop_constraint('fk_inventory_items_vendor_id_vendors', type_='foreignkey')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('storage')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('units_per_package')
        batch_op.drop_column('volume_ml')
        batch_op.drop_column('vial_size_unit')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_owner_id'))

    op.drop_table('vendors')
    # ### end Alembic commands ###
